services:
  api: &main_app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: nir_myrmiaka:${NIR_MYRMIAKA_VERSION:-latest}
    env_file:
      - .env
    volumes:
      - nir_myrmiaka-db-data:/db_data/

volumes:
  nir_myrmiaka-db-data:
    name: nir_myrmiaka-db-data
