bash
Copy
#!/bin/bash
set -e

# Path to the SQLite database file
DB_FILE="/db_data/db.sqlite3"

# Create the database file if it doesn't exist
if [ ! -f "$DB_FILE" ]; then
  echo "Database file not found. Creating an empty database..."
  touch "$DB_FILE"
fi

# Check if the database is up to date
if alembic current | grep -q "head"; then
  echo "Database is up to date. No migrations needed."
else
  echo "Database is not up to date. Applying Alembic migrations..."
  alembic upgrade head
fi

# Autogenerate revisions if enabled
if [ "$AUTOGENERATE_REVISIONS" = "true" ]; then
  echo "Autogenerating Alembic revision..."
  alembic revision --autogenerate -m "autogenerated revision"
  alembic upgrade head
fi

# Run tests
if [ "$RUN_TESTS" = "true" ]; then
  echo "Running pytest..."
  pytest tests/ -vv
else
  echo "Skipping tests..."
fi


# Run the main application command
echo "Starting the application..."
exec "$@"