"""autogenerated revision

Revision ID: 32bad1c5d369
Revises: 
Create Date: 2025-03-23 15:15:37.496974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32bad1c5d369'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_researchwork',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submission_topic_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('research_work_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['research_work_id'], ['base_researchwork.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('base_topic', schema=None) as batch_op:
        batch_op.create_index('base_topic_research_work_id_f512bc53', ['research_work_id'], unique=False)

    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('middle_name', sa.String(length=30), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['users_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.create_index('merged_user_profile_group_id_d32cb94c', ['group_id'], unique=False)

    op.create_table('base_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['user_profile.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('base_assignment', schema=None) as batch_op:
        batch_op.create_index('base_assignment_student_id_28cc3722', ['student_id'], unique=False)
        batch_op.create_index('base_assignment_teacher_id_829fa074', ['teacher_id'], unique=False)

    op.create_table('base_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('submission_title', sa.String(length=100), nullable=True),
    sa.Column('semester', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('researchwork_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['base_assignment.id'], ),
    sa.ForeignKeyConstraint(['researchwork_id'], ['base_researchwork.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('base_submission', schema=None) as batch_op:
        batch_op.create_index('base_submission_assignment_id_907d9d53', ['assignment_id'], unique=False)
        batch_op.create_index('base_submission_research_work_id_6a4c7968', ['researchwork_id'], unique=False)

    op.create_table('submission_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['submission_topic_comment.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['base_submission.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['base_topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('topic_submission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_submission_id'], ['submission_topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('base_file')
    op.drop_table('submission_topic')
    with op.batch_alter_table('base_submission', schema=None) as batch_op:
        batch_op.drop_index('base_submission_research_work_id_6a4c7968')
        batch_op.drop_index('base_submission_assignment_id_907d9d53')

    op.drop_table('base_submission')
    with op.batch_alter_table('base_assignment', schema=None) as batch_op:
        batch_op.drop_index('base_assignment_teacher_id_829fa074')
        batch_op.drop_index('base_assignment_student_id_28cc3722')

    op.drop_table('base_assignment')
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_index('merged_user_profile_group_id_d32cb94c')

    op.drop_table('user_profile')
    with op.batch_alter_table('base_topic', schema=None) as batch_op:
        batch_op.drop_index('base_topic_research_work_id_f512bc53')

    op.drop_table('base_topic')
    op.drop_table('users_group')
    op.drop_table('submission_topic_comment')
    op.drop_table('base_researchwork')
    # ### end Alembic commands ###
