"""autogenerated revision

Revision ID: 95d3c39f26df
Revises: b54112407b6c
Create Date: 2025-03-23 15:40:08.742867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95d3c39f26df'
down_revision: Union[str, None] = 'b54112407b6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_reviewed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_file', schema=None) as batch_op:
        batch_op.drop_column('is_reviewed')

    # ### end Alembic commands ###
