"""autogenerated revision

Revision ID: b37645238c48
Revises: 1628d3bc4a1b
Create Date: 2025-03-23 13:26:18.041367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b37645238c48'
down_revision: Union[str, None] = '1628d3bc4a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('base_submission', sa.Column('submission_title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_submission', 'submission_title')
    # ### end Alembic commands ###
