"""autogenerated revision

Revision ID: d2a398d48de1
Revises: 38f83254e14d
Create Date: 2025-03-25 17:32:50.098039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2a398d48de1'
down_revision: Union[str, None] = '38f83254e14d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(), nullable=False))
        batch_op.drop_column('filename')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
