"""autogenerated revision

Revision ID: f10b2c67d183
Revises: 
Create Date: 2025-03-22 12:59:59.628399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f10b2c67d183'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_researchwork',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('research_work_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['research_work_id'], ['base_researchwork.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('base_topic_research_work_id_f512bc53', 'base_topic', ['research_work_id'], unique=False)
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('middle_name', sa.String(length=30), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['users_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('merged_user_profile_group_id_d32cb94c', 'user_profile', ['group_id'], unique=False)
    op.create_table('base_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_accepted', sa.Boolean(), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['user_profile.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('base_assignment_student_id_28cc3722', 'base_assignment', ['student_id'], unique=False)
    op.create_index('base_assignment_teacher_id_829fa074', 'base_assignment', ['teacher_id'], unique=False)
    op.create_table('base_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('researchwork_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['base_assignment.id'], ),
    sa.ForeignKeyConstraint(['researchwork_id'], ['base_researchwork.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('base_submission_assignment_id_907d9d53', 'base_submission', ['assignment_id'], unique=False)
    op.create_index('base_submission_research_work_id_6a4c7968', 'base_submission', ['researchwork_id'], unique=False)
    op.create_table('submission_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_accepted', sa.Boolean(), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['base_submission.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['base_topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('base_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('topic_submission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_submission_id'], ['submission_topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('base_file')
    op.drop_table('submission_topic')
    op.drop_index('base_submission_research_work_id_6a4c7968', table_name='base_submission')
    op.drop_index('base_submission_assignment_id_907d9d53', table_name='base_submission')
    op.drop_table('base_submission')
    op.drop_index('base_assignment_teacher_id_829fa074', table_name='base_assignment')
    op.drop_index('base_assignment_student_id_28cc3722', table_name='base_assignment')
    op.drop_table('base_assignment')
    op.drop_index('merged_user_profile_group_id_d32cb94c', table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_index('base_topic_research_work_id_f512bc53', table_name='base_topic')
    op.drop_table('base_topic')
    op.drop_table('users_group')
    op.drop_table('base_researchwork')
    # ### end Alembic commands ###
