"""autogenerated revision

Revision ID: f6c10a54b439
Revises: d2a398d48de1
Create Date: 2025-03-25 17:46:51.924193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6c10a54b439'
down_revision: Union[str, None] = 'd2a398d48de1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_filename', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('content_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('storage_path', sa.String(), nullable=False))
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('base_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('storage_path')
        batch_op.drop_column('size')
        batch_op.drop_column('content_type')
        batch_op.drop_column('original_filename')

    # ### end Alembic commands ###
